# Generated by Django 3.2 on 2023-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
