version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8001:8000"
    container_name: fscl-file-portal
    volumes:
      - .:/app
    env_file:
      - ./.env
    networks:
      - fscl_network
    depends_on:
      - redis
      - celery

  redis:
    image: redis:alpine
    command: redis-server
    container_name: redis
    networks:
      - fscl_network

  celery:
    restart: always
    build:
      context: .
    command: celery -A fileapp worker --pool=solo -l info
    volumes:
      - .:/app
    container_name: celery
    env_file:
      - ./.env
    networks:
      - fscl_network

networks:
  fscl_network:
    driver: bridge
